export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body>
        <nav className="bg-red-500 w-full">navbar</nav>
        {children}
        <footer>rodapé</footer>
      </body>
    </html>
  )
}
